version: '3.7'

services:
  redis:
    image: redis
     
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn exonsurfer.wsgi:application --bind 0.0.0.0:8000 --timeout 600  --access-logfile /home/app/web/gunicorn-access.log --error-logfile /home/app/web/gunicorn-access.log 
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/Data
    expose:
      - 8000



  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/Data
    ports:
      - 8889:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: