version: '3.7'

services:
  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379
     
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn exonsurfer.wsgi:application --bind 0.0.0.0:8000 --timeout 600  --access-logfile /home/app/web/gunicorn-access.log --error-logfile /home/app/web/gunicorn-access.log 
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/Data
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  rq_high:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: python3 manage.py rqworker high 
    links:
      - redis
    volumes:
      - media_volume:/home/app/web/Data
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db
      - redis
    entrypoint: ["/home/app/web/entrypoint_2.sh"]

  rq_low:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: python3 manage.py rqworker low 
    links:
      - redis
    volumes:
      - media_volume:/home/app/web/Data
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db
      - redis
    entrypoint: ["/home/app/web/entrypoint_2.sh"]

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/Data
    ports:
      - 8889:80
    depends_on:
      - web
      
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  static_volume:
  media_volume:
  postgres_data:
