# Generated by Django 3.2 on 2023-02-15 15:55

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import primerblast.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_opt_size', models.IntegerField(default=20)),
                ('primer_min_size', models.IntegerField(default=17)),
                ('primer_max_size', models.IntegerField(default=35)),
                ('primer_opt_tm', models.FloatField(default=59)),
                ('primer_min_tm', models.FloatField(default=57.5)),
                ('primer_max_tm', models.FloatField(default=60.5)),
                ('primer_opt_gc', models.IntegerField(default=50)),
                ('primer_min_gc', models.IntegerField(default=20)),
                ('primer_max_gc', models.IntegerField(default=80)),
                ('primer_product_size_min', models.IntegerField(default=170)),
                ('primer_product_size_opt', models.IntegerField(default=200)),
                ('primer_product_size_max', models.IntegerField(default=250)),
                ('primer_product_opt_tm', models.FloatField(default=80)),
                ('primer_product_min_tm', models.FloatField(default=65)),
                ('primer_product_max_tm', models.FloatField(default=90)),
                ('primer_salt_divalent', models.FloatField(default=1.5)),
                ('primer_salt_monovalent', models.FloatField(default=50)),
                ('primer_dntp_conc', models.FloatField(default=0.6)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('transcript', models.CharField(max_length=100)),
                ('is_run', models.BooleanField(default=False)),
                ('primer_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primerblast.primerconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlastFile', models.FileField(max_length=250, storage=django.core.files.storage.FileSystemStorage(location='/home/q053pm/biotools/ExonSurferWeb/web/exonsurfer/Data'), upload_to=primerblast.models.Result.get_session_path)),
                ('PrimerFile', models.FileField(max_length=250, storage=django.core.files.storage.FileSystemStorage(location='/home/q053pm/biotools/ExonSurferWeb/web/exonsurfer/Data'), upload_to=primerblast.models.Result.get_session_path)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primerblast.session')),
            ],
        ),
    ]
