# Generated by Django 3.2 on 2023-02-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='gene_version',
        ),
    ]
