# Generated by Django 3.2 on 2023-02-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl', '0003_remove_gene_transcript_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='transcript_version',
        ),
        migrations.AlterField(
            model_name='gene',
            name='strand',
            field=models.CharField(max_length=10),
        ),
    ]
