# Generated by Django 3.2 on 2023-01-24 15:24

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import primerblast.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_opt_size', models.IntegerField()),
                ('primer_min_size', models.IntegerField()),
                ('primer_max_size', models.IntegerField()),
                ('primer_opt_tm', models.FloatField()),
                ('primer_min_tm', models.FloatField()),
                ('primer_max_tm', models.FloatField()),
                ('primer_opt_gc', models.IntegerField()),
                ('primer_min_gc', models.IntegerField()),
                ('primer_max_gc', models.IntegerField()),
                ('primer_product_size_min', models.IntegerField()),
                ('primer_product_size_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('species', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('transcript', models.CharField(max_length=100)),
                ('primer_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primerblast.primerconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlastFile', models.FileField(max_length=250, storage=django.core.files.storage.FileSystemStorage(location='/home/q053pm/biotools/ExonSurferWeb/web/exonsurfer/Data'), upload_to=primerblast.models.Result.get_session_path)),
                ('PrimerFile', models.FileField(max_length=250, storage=django.core.files.storage.FileSystemStorage(location='/home/q053pm/biotools/ExonSurferWeb/web/exonsurfer/Data'), upload_to=primerblast.models.Result.get_session_path)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primerblast.session')),
            ],
        ),
    ]
