# Generated by Django 3.2 on 2023-01-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerblast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_run',
            field=models.BooleanField(default=False),
        ),
    ]
