# Generated by Django 3.2 on 2023-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerblast', '0002_session_is_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerconfig',
            name='primer_dntp_conc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primerconfig',
            name='primer_product_max_tm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primerconfig',
            name='primer_product_min_tm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primerconfig',
            name='primer_product_opt_tm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primerconfig',
            name='primer_salt_divalent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='primerconfig',
            name='primer_salt_monovalent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
