# Generated by Django 3.2 on 2023-02-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerblast', '0003_auto_20230201_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_dntp_conc',
            field=models.FloatField(default=0.6),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_max_gc',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_max_size',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_max_tm',
            field=models.FloatField(default=60.5),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_min_gc',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_min_size',
            field=models.IntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_min_tm',
            field=models.FloatField(default=57.5),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_opt_gc',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_opt_size',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_opt_tm',
            field=models.FloatField(default=59),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_product_max_tm',
            field=models.FloatField(default=90),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_product_min_tm',
            field=models.FloatField(default=65),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_product_opt_tm',
            field=models.FloatField(default=80),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_product_size_max',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_product_size_min',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_salt_divalent',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='primerconfig',
            name='primer_salt_monovalent',
            field=models.FloatField(default=50),
        ),
    ]
