# Generated by Django 3.2 on 2023-02-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerblast', '0004_auto_20230201_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='primerconfig',
            name='primer_product_size_opt',
            field=models.IntegerField(default=170),
        ),
    ]
